name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set env variables for Docker builds
      run: |
        echo "DOCKER_CLI_EXPERIMENTAL=enabled" >> $GITHUB_ENV
        echo "DOCKERHUB_REPO=fogsyio" >> $GITHUB_ENV
    - name: Docker enable experimental feature
      run: |
        echo '{"experimental": true}' | sudo tee /etc/docker/daemon.json
        sudo service docker restart
        cat /etc/docker/daemon.json
    - name: Download qemu for multi-arch builds
      run: sudo apt-get install qemu-user-static
    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u ${{ secrets.DOCKERHUB_USER }} --password-stdin
    - name: Build and push Docker Images
      run: >
        bash docker-build.sh
        ${{ env.DOCKERHUB_REPO }}
